### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by ryoppippi** [zigcv/zigcv#25]
Hmm....

**Comment by wbehrens-on-gh** [comment]
might help

`flake.nix`
```nix
{
  description = "A nix-zig template";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  };

  outputs = { self, nixpkgs }:
    let
      pkgs = nixpkgs.legacyPackages.x86_64-linux;
    in
    {
      devShells.x86_64-linux = {
        # Shell environment for development use 
        #default = pkgs.mkShell {
      	default = (pkgs.buildFHSUserEnv {
          name = "dev";
          targetPkgs = pkgs: with pkgs; [ 
						zig 
						zls nil 
						git bat neovim 
						opencv
					];
        }).env;
      };
    };
}
```

In case you're not familiar with [nix](https://nixos.org/), you should just have to run `nix develop` with that present.

Using the above I get the build failure
![image](https://github.com/ryoppippi/zigcv/assets/35979547/a456accd-1ef4-4b7a-97e0-6cb146f4fd64)

This is after adding
```zig
exe.addIncludePath("/usr/include/");
exe.addIncludePath("/usr/include/opencv4");
```
to `libs.zig`

zig version: 0.10.1

**Comment by ryoppippi** [comment]
Thanks for your PR!!
And, Okay, so I gonna switch back the zig version for ci to 0.10.1.
But we need to upgrade zig 0.11.0 soon.
I haven't catch up the next version of zig for a while, but I'll do it

**Comment by ryoppippi** [comment]
@wbehrens-on-gh 
Hi I'm back.
I'll use this nix config.

**Comment by ryoppippi** [comment]
@wbehrens-on-gh 
Currently, I added devbox configuration, and it works on my macOS (I haven't check on linux)
I didn't realise how great NIX was until recently and didn't really understand your suggestion. Sorry.
